language: python
sudo: false
env:
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=py36
install:
    - travis_retry pip install tox
script:
    - tox
notifications:
    email: false
